{
 "title": "System Overview",
 "tags": [ "Linux" ],
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "System Specifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count without(cpu, mode) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum(rate(node_cpu_seconds_total[5m])) by (instance) - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)) \n/ sum(rate(node_cpu_seconds_total[5m])) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory Usage Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Used Memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap Usage %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Network Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Download Speed (Bytes Per Second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Upload Speed (Bytes per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filesystem Usage Percentages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Root Filesystem",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 - (\n    node_filesystem_avail_bytes{mountpoint=~\"/\"} \n    / \n    node_filesystem_size_bytes{mountpoint=~\"/\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Game Drive",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 - (\n    node_filesystem_avail_bytes{mountpoint=\"/mnt/games\"} \n    / \n    node_filesystem_size_bytes{mountpoint=\"/mnt/games\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media Drive Usage %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (\n  1 - (\n    node_filesystem_avail_bytes{mountpoint=\"/mnt/media\"} \n    / \n    node_filesystem_size_bytes{mountpoint=\"/mnt/media\"}\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}